Configuracion As screen:

    Rectangle1_4 As rectangle:
        BorderColor: =RGBA(255, 237, 74, 1)
        Fill: =RGBA(69, 53, 10, 1)
        Height: =129
        Width: =640
        ZIndex: =1

    Label15 As label:
        Height: =100
        Size: =30
        Text: ="Setting"
        Width: =245
        X: =33
        Y: =129
        ZIndex: =3

    TextInput1 As text:
        BorderColor: =RGBA(54, 176, 75, 1)
        BorderThickness: =5
        Default: ="Change Password"
        Height: =111
        Size: =21
        Width: =539
        X: =71
        Y: =462
        ZIndex: =5

    Label16 As label:
        Align: =Align.Center
        Height: =80
        Size: =30
        Text: ="Argel Martinez"
        Width: =326
        X: =179
        Y: =358
        ZIndex: =6

    TextInput7 As text:
        BorderColor: =RGBA(54, 176, 75, 1)
        BorderThickness: =5
        Default: ="Change Email"
        Height: =93
        Size: =21
        Width: =539
        X: =71
        Y: =587
        ZIndex: =7

    TextInput11 As text:
        BorderColor: =RGBA(54, 176, 75, 1)
        BorderThickness: =5
        Default: ="Change Account"
        Height: =97
        Size: =21
        Width: =539
        X: =71
        Y: =693
        ZIndex: =9

    Image18_2 As image:
        Height: =232
        Image: =user
        Width: =276
        X: =204
        Y: =159
        ZIndex: =11

    Image7_2 As image:
        Height: =165
        Image: ='ddddd-removebg-preview (1)'
        ImagePosition: =ImagePosition.Fill
        Width: =239
        X: =130
        Y: =11
        ZIndex: =12

    Label2_2 As label:
        Align: =Align.Center
        Color: =RGBA(54, 176, 75, 1)
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =96
        Size: =30
        Text: ="AGROTEC"
        Width: =332
        X: =278
        Y: =16
        ZIndex: =13

    Icon7_1 As icon.ArrowLeft:
        Color: =RGBA(255, 255, 255, 1)
        Height: =74
        Icon: =Icon.ArrowLeft
        Width: =89
        X: =12
        Y: =19
        ZIndex: =14

    Button5 As button:
        Fill: =RGBA(54, 176, 75, 1)
        Height: =79
        Size: =24
        Text: ="Save"
        Width: =236
        X: =369
        Y: =859
        ZIndex: =15

