Productos As screen:
    BackgroundImage: =

    Rectangle1_1 As rectangle:
        BorderColor: =RGBA(255, 237, 74, 1)
        Fill: =RGBA(69, 53, 10, 1)
        Height: =129
        Width: =640
        ZIndex: =1

    Rectangle2_5 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =8
        Fill: =RGBA(255, 255, 255, 1)
        Height: =156
        Width: =187
        X: =24
        Y: =94
        ZIndex: =2

    Label11 As label:
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =70
        Size: =30
        Text: ="PRODUCTS"
        Width: =560
        X: =24
        Y: =293
        ZIndex: =3

    Arrow3 As arrow.backArrow:
        BorderColor: =RGBA(255, 255, 255, 1)
        Fill: =RGBA(255, 255, 255, 1)
        Height: =70
        OnSelect: =Navigate(usuarios,ScreenTransition.Fade)
        Width: =66
        X: =24
        Y: =24
        ZIndex: =4

    Rectangle3 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =10
        Fill: =RGBA(255, 255, 255, 1)
        Height: =146
        Width: =640
        Y: =990
        ZIndex: =5

    TextInput10 As text:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =6
        Default: ="COMMENTS"
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =146
        Size: =35
        Width: =640
        Y: =990
        ZIndex: =6

    Image14 As image:
        Height: =163
        Image: =USUARIOO
        Width: =173
        X: =38
        Y: =94
        ZIndex: =7

    Rectangle2_13 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =8
        Fill: =RGBA(255, 255, 255, 1)
        Height: =142
        Width: =167
        X: =438
        Y: =414
        ZIndex: =15

    Rectangle2_15 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =8
        Fill: =RGBA(255, 255, 255, 1)
        Height: =142
        Width: =167
        X: =231
        Y: =414
        ZIndex: =17

    Rectangle2_16 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =8
        Fill: =RGBA(255, 255, 255, 1)
        Height: =142
        Width: =167
        X: =24
        Y: =414
        ZIndex: =18

    Rectangle2_14 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =8
        Fill: =RGBA(255, 255, 255, 1)
        Height: =142
        Width: =167
        X: =24
        Y: =690
        ZIndex: =19

    Rectangle2_17 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =8
        Fill: =RGBA(255, 255, 255, 1)
        Height: =142
        Width: =167
        X: =231
        Y: =690
        ZIndex: =20

    Rectangle2_18 As rectangle:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =8
        Fill: =RGBA(255, 255, 255, 1)
        Height: =142
        Width: =167
        X: =438
        Y: =690
        ZIndex: =21

    Label12 As label:
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =92
        Size: =35
        Text: ="Roger Peets"
        Width: =340
        X: =231
        Y: =165
        ZIndex: =22

    Image15 As image:
        Height: =116
        Image: =images
        Width: =158
        X: =38
        Y: =427
        ZIndex: =23

    Label13 As label:
        Align: =Align.Center
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =68
        Size: =25
        Text: =" Cob 1.00$"
        Width: =130
        X: =38
        Y: =570
        ZIndex: =24

    Image16 As image:
        Height: =116
        Image: ='tomate_perita1-e9d38b711ead101c6115939095879020-480-0'
        Width: =167
        X: =231
        Y: =427
        ZIndex: =25

    Label13_1 As label:
        Align: =Align.Center
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =82
        Size: =19
        Text: =" Perita  Tomato   LB 0.50$"
        Width: =136
        X: =245
        Y: =570
        ZIndex: =26

    Image17 As image:
        Height: =150
        Image: =descarga_2
        Width: =130
        X: =454
        Y: =414
        ZIndex: =27

    Label5 As label:
        Align: =Align.Center
        Font: =Font.'Lato Black'
        Height: =66
        Size: =21
        Text: ="onion  LB  0.75"
        Width: =111
        X: =460
        Y: =572
        ZIndex: =28

    Image8 As image:
        Height: =154
        Image: ='OIP (1)'
        Width: =144
        X: =38
        Y: =678
        ZIndex: =29

    Label9 As label:
        Align: =Align.Center
        Font: =Font.'Lato Black'
        Height: =112
        Size: =21
        Text: ="orange 5x1.00$"
        Width: =182
        X: =12
        Y: =818
        ZIndex: =30

    Image11 As image:
        Height: =108
        Image: ='transparent-strawberry-download-strawberry-png-image-fruits-png-png-ima5e5a8993ccce17.3696195215829917638389'
        Width: =174
        X: =231
        Y: =702
        ZIndex: =31

    Label10 As label:
        Align: =Align.Center
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =135
        Size: =21
        Text: ="Strawberries 5.00$"
        Width: =225
        X: =197
        Y: =818
        ZIndex: =32

    Label14 As label:
        Align: =Align.Center
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =130
        Size: =21
        Text: ="Tangerines  5x1.00$"
        Width: =191
        X: =420
        Y: =809
        ZIndex: =34

    Image18 As image:
        Height: =192
        Image: ='860-8606992_imagens-de-mandarina-en-png'
        Width: =130
        X: =454
        Y: =681
        ZIndex: =35

